### Listar Orders (REST)
GET http://localhost:8080/order
Accept: application/json

### Criar Order (REST)
POST http://localhost:8080/order
Content-Type: application/json

{
    "price": 100.00,
    "tax": 10.00
}

### Listar Orders (GraphQL)
POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "query { orders { id price tax final_price } }"
}

### Criar Order (GraphQL)
POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "mutation { createOrder(input: { price: 100.00, tax: 10.00 }) { id price tax final_price } }"
} 